### ISSUE TITLE
Try Medium's font color

### ISSUE THREAD

**Issue by dtoma** [dtoma/dtoma.github.io#4]
```css
body {
  rgba(0,0,0,.84);
  font-family: Georgia,Cambria,"Times New Roman",Times,serif;
}
caption { rgba(0,0,0,.54) } /* reduce emphasis */
```
